using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._Arcane.ERP.UI;

[GenerateTypedNameReferences]
public sealed partial class CreampieConfirmWindow : FancyWindow
{
    public event Action<bool>? OnConfirm;

    public NetEntity User { get; set; }
    public NetEntity Target { get; set; }

    public CreampieConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        YesButton.OnPressed += _ => OnConfirm?.Invoke(true);
        NoButton.OnPressed += _ => OnConfirm?.Invoke(false);
    }
}
